CREATE TABLE PUBLIC.TRANSACTIONS (
	"Date" DATE,
	"Type" VARCHAR_IGNORECASE,
	AMOUNT DECFLOAT,
	"Source" VARCHAR_IGNORECASE,
	ID INTEGER NOT NULL AUTO_INCREMENT
);
INSERT INTO PUBLIC.TRANSACTIONS ("Date","Type",AMOUNT,"Source") VALUES
	 ('2021-11-06','Expense',5000,'Manure');